name: Label Codex PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add automerge label for codex branches
        uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'codex/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
